import { ProfileCharacter } from '@/types/modules/users';

export const profiles: ProfileCharacter[] = [
  {
    id: 'jju',
    name: '쮸',
    animal: 'mouse',
    description: '세상에서 제일 빠른 치즈 감별사! 🧀',
    imageUrl: '/images/profile/jju.png',
    quote: '달콤함을 찾아 어디든 떠나는 커피&디저트 탐험가!',
    item: ['디저트', '카페투어', '치즈', '사진', '후각천재'],
  },
  {
    id: 'moong',
    name: '뭉',
    animal: 'cow',
    description: '불멍과 자연을 사랑하는 여유로운 캠핑 마스터 🌿',
    imageUrl: '/images/profile/moong.png',
    quote: '불멍과 자연의 바람, 초록과 가까운 삶을 즐겨요.',
    item: ['캠핑', '풀', '불멍', '자연 산책', '하늘보기'],
  },
  {
    id: 'hoya',
    name: '호야',
    animal: 'tiger',
    description: '복(福) 봉투를 꼭 쥔 용맹하고 귀여운 호랑이 🐯🧧',
    imageUrl: '/images/profile/hoya.png',
    quote: '아침은 차트 분석! 경제 뉴스는 기본이죠.',
    item: ['재테크', '자기개발', '북클럽', '투자일지', '계획'],
  },
  {
    id: 'kongi',
    name: '콩이',
    animal: 'rabbit',
    description: '꽃과 햇살, 야외 스케치에 진심인 감성 토끼 🌷',
    imageUrl: '/images/profile/kongi.png',
    quote: '햇살 아래 꽃을 그리고, 마음을 적셔요.',
    item: ['꽃', '스케치북', '수채화', '피크닉', '야외'],
  },
  {
    id: 'loony',
    name: '루니',
    animal: 'dragon',
    description: '구름 위에서 소설을 쓰는 몽상가 드래곤 ☁️👑',
    imageUrl: '/images/profile/loony.png',
    quote: '생각을 구름에 담아, 한 문장 한 문장 엮어가요.',
    item: ['다이어리', '글쓰기', '공상', '소설', '펜'],
  },
  {
    id: 'ningyi',
    name: '닝이',
    animal: 'snake',
    description: '조용한 밤, 와인 한 잔과 함께 감성 정리를 즐기는 뱀 🍷',
    imageUrl: '/images/profile/ningyi.png',
    quote: '혼자 마시는 와인, 오늘 하루의 온도를 기록해요.',
    item: ['와인', '밤', '조용한공간', '잔잔한음악', '감성'],
  },
  {
    id: 'daro',
    name: '다로',
    animal: 'horse',
    description: '트렌드에 민감한 뷰티 셀럽 말 💄',
    imageUrl: '/images/profile/daro.png',
    quote: '겉모습도, 내면도. 나는 오늘의 유행이에요.',
    item: ['자기관찰', '뷰티템', '거울', '트렌드', '자기관리'],
  },
  {
    id: 'mongsil',
    name: '몽실',
    animal: 'sheep',
    description: '따뜻한 실뭉치와 쿠키, 낮잠을 사랑하는 몽글몽글 양 🍪',
    imageUrl: '/images/profile/mongsil.png',
    quote: '실 한 올 한 올에 마음을 담는 몽글몽글 집순이',
    item: ['뜨개질', '실', '소파', '베개', '티타임'],
  },
  {
    id: 'monkiring',
    name: '몽키링',
    animal: 'monkey',
    description: '헬스엔 진심, 장난도 놓치지 않는 다재다능 원숭이 🙈',
    imageUrl: '/images/profile/monkiring.png',
    quote: '으쓱! 철없는 장난도 진심인 근손실 무서운 원숭이!',
    item: ['장난', '헬스', '덤벨', '도파민', '운동루틴'],
  },
  {
    id: 'ttotto',
    name: '또또',
    animal: 'chick',
    description: '좋아하는 걸 찾는 중! 이것저것 도전해보는 heyB 마스코트 🐣',
    imageUrl: '/images/profile/ttotto.png',
    quote: '아직 좋아하는 걸 못찾았지만, 언젠간 꼭 찾고말거야!',
    item: ['호기심', '일기장', '찍먹', '도전', '친구들'],
  },
  {
    id: 'doori',
    name: '두리',
    animal: 'dog',
    description: '감성 충만! 음악과 독서를 사랑하는 다정한 플래너 📒',
    imageUrl: '/images/profile/doori.png',
    quote: '모든 친구의 하루를 챙기는, 다정한 시간 기록가',
    item: ['다꾸', '책', '음악', '스티커', '시간표'],
  },
  {
    id: 'kkuying',
    name: '꾸잉',
    animal: 'pig',
    description: '맛집 탐방과 사진 남기기를 사랑하는 먹보 천재 😋',
    imageUrl: '/images/profile/kkuying.png',
    quote: '냄새만 맡아도 알지, 오늘은 이 집이야!',
    item: ['맛집', '포크', '숟가락', '사진', '먹방'],
  },
];
